services:
  collegecontrolsystem.presentation:
    image: ${DOCKER_REGISTRY-}collegecontrolsystempresentation
    build:
      context: .
      dockerfile: CollegeControlSystem.Presentation/Dockerfile
